# Generated by Django 6.0 on 2025-12-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='hobby',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pw',
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
