# Generated by Django 6.0 on 2025-12-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=1)),
                ('grade', models.IntegerField(default=1)),
                ('gender', models.CharField(max_length=10)),
                ('hobby', models.CharField(max_length=100)),
            ],
        ),
    ]
